tensor_shape: [482, 406, 93]
satellite_descriptor: '/home/kulikov/dineof3/test/satellite_descriptor.csv' 
input_stem: Input
output_stem: Output
static_grid_stem: static_grid
interpolated_stem: interpolated
unified_tensor_stem: unified_tensor
timeline_stem: timeline
only_years: null
random_seed: 2434311

logs: './test/reconstruction_logs'
trials: 30
start_trial: 0


# Shell command to call GHER DINEOF
# Details: http://modb.oce.ulg.ac.be/mediawiki/index.php/DINEOF
dineof_executer: "/home/kulikov/dineof-3.0/dineof"

# time vector (necessary if B_DIFF option is activated in ppdef.h
# necessary files:
# alpha: parameter specifying the strength of the filter
# numit: number of iterations for the filter
# See http://www.ocean-sci.net/5/475/2009/os-5-475-2009.pdf for more information
alpha: 0.0
numit: 3

# Give 'nev' the maximum of number of modes you allow to compute,
# Dineof will stop after computing the optimal number of modes + 3 extra modes
# for robust optimum detection.
nev: 20

# Give 'neini' the minimum  number of modes you want to compute
neini: 5

# Give 'ncv' the maximal size for the Krylov subspace
# (Do not change it as soon as ncv > nev+5)
# ncv must also be smaller than the temporal size of your matrix
ncv: 16

# Give 'tol' the treshold for Lanczos convergence
# By default 1.e-8 is quite reasonable
tol: 1.0e-8

# Parameter 'nitemax' defining the maximum number of iteration allowed for the stabilisation
# of eofs obtained by the cycle ((eof decomposition <-> truncated reconstruction and
# replacement of missing data)). An automatic criteria is defined by the following parameter
# 'itstop' to go faster
nitemax: 100

# Parameter 'toliter' is a precision criteria defining the threshold of automatic stopping
# of dineof iterations, once the ratio (rms of successive missing data
# reconstruction)/stdv(existing data) becomes lower then 'toliter'.s
toliter: 1.0e-3

# Parameter 'rec' for complete reconstruction of the matrix
# rec=1 will reconstruct all points; rec=0 only missing points
rec: 0

# Parameter 'eof' for writing the left and right modes of the
# input matrix. Disabled by default. To activate, set to 1
eof: 1

# Parameter 'norm' to activate the normalisation of the input matrix
# for multivariate case. Disabled by default. To activate, set to 1
norm: 0

# 'seed' to initialize the random number generator
seed: 2434311
